### ISSUE TITLE
io.grpc:grpc-okhttp

### ISSUE THREAD

**Issue by harshemtec** [abhi007tyagi/DialogflowChat#10]
I am using this lib as you mentioned  implementation 'io.grpc:grpc-okhttp:1.21.0' but it is giving me following error:

```
2020-04-12 15:38:53.983 771-771/com.example.demodialogflowapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.demodialogflowapplication, PID: 771
    java.lang.NoSuchFieldError: No static field IS_RESTRICTED_APPENGINE of type Z in class Lio/grpc/internal/GrpcUtil; or its superclasses (declaration of 'io.grpc.internal.GrpcUtil' appears in /data/app/com.example.demodialogflowapplication-JIu4uLQyRWHPrbfASX5UQQ==/base.apk!classes4.dex)
        at io.grpc.okhttp.OkHttpChannelBuilder.createSslSocketFactory(OkHttpChannelBuilder.java:451)
        at io.grpc.okhttp.OkHttpChannelBuilder.buildTransportFactory(OkHttpChannelBuilder.java:418)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:543)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:304)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1500(InstantiatingGrpcChannelProvider.java:71)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:202)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:209)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:192)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
        at com.google.cloud.dialogflow.v2beta1.stub.GrpcSessionsStub.create(GrpcSessionsStub.java:78)
        at com.google.cloud.dialogflow.v2beta1.stub.SessionsStubSettings.createStub(SessionsStubSettings.java:108)
        at com.google.cloud.dialogflow.v2beta1.SessionsClient.<init>(SessionsClient.java:132)
        at com.google.cloud.dialogflow.v2beta1.SessionsClient.create(SessionsClient.java:114)
        at com.example.demodialogflowapplication.MainActivity.initV2Chatbot(MainActivity.kt:58)
        at com.example.demodialogflowapplication.MainActivity.onCreate(MainActivity.kt:30)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
If I remove this lib it will throwing me this error: 

`error while creating SessionsClient`

Could you please help me with this?

**Comment by abhi007tyagi** [comment]
try and change version if you are using latest dialogflow version.

**Comment by abhi007tyagi** [comment]
See updated code. I have tested it on Android API version 23 and 29

**Comment by harshemtec** [comment]
Thank you for your response. I will try updated code.
